apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: dev-host
  title: Dev Flash Host (Environment)
  description: โฮสต์สำหรับการพัฒนา (DEV)
  annotations:
    backstage.io/host: flashdev.deves.co.th
    backstage.io/host-ip: 10.20.30.11
spec:
  type: environment
  owner: guests
