apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DVS_CONFIRMPOLICYBACKEND-db
  description: Stores DVS_CONFIRMPOLICYBACKEND
  annotations:
    dev/host: flashdev.deves.co.th
spec:
  type: database
  lifecycle: production
  owner: guests
  system: policy-request-system
