apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: EWIPOLICY-db
  description: Stores EWIPOLICY
  annotations:
    dev/status: active
    dev/ip: 192.168.3.83
spec:
  type: database
  lifecycle: production
  owner: guests
  system: policy-request-system
