apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ta-policy-request-api
  description: Insurance TA Policy
  tags:
    - dotnet-framework-472
    - c-charp
  links:
    - url: http://localhost:8888/explore/default/9a4a4c41-2388-4478-a6ad-da2d2f828317
      title: API Registry
      icon: dashboard
      type: admin-dashboard
spec:
  type: api
  lifecycle: production
  owner: guests
  system: policies
