apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ta-policy-request-api
  description: TA API
  tags:
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/webhook-example.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: http://localhost:8080/apis/registry/v3/groups/default/artifacts/9a4a4c41-2388-4478-a6ad-da2d2f828317/versions/branch=latest/content
